insert into student (name, birthday, groupnumber) values ('John', '1997-03-17', 1);
insert into student (name, birthday, groupnumber) values ('Chris', '1997-04-17', 1);
insert into student (name, birthday, groupnumber) values ('Carl', '1997-03-19', 1);
insert into student (name, birthday, groupnumber) values ('Oliver', '1996-07-15', 2);
insert into student (name, birthday, groupnumber) values ('James', '1996-08-15', 2);
insert into student (name, birthday, groupnumber) values ('Lucas', '1996-07-25', 2);
insert into student (name, birthday, groupnumber) values ('Henry', '1996-01-25', 2);
insert into student (name, birthday, groupnumber) values ('Jacob', '1995-09-15', 3);
insert into student (name, birthday, groupnumber) values ('Logan', '1995-07-09', 3);
insert into student (name, birthday, groupnumber) values ('Ashton', '1994-07-20', 4);
insert into student (name, birthday, groupnumber) values ('Kyle', '1994-04-07', 4);
insert into student (name, birthday, groupnumber) values ('Max', '1993-07-15', 5);
insert into student (name, birthday, groupnumber) values ('Victor', '1993-07-01', 5);
insert into subject (name, grade) values ('Art', 1);
insert into subject (name, grade) values ('Music', 1);
insert into subject (name, grade) values ('Geography', 2);
insert into subject (name, grade) values ('History', 2);
insert into subject (name, grade) values ('PE', 3);
insert into subject (name, grade) values ('Math', 3);
insert into subject (name, grade) values ('Science', 4);
insert into subject (name, grade) values ('IT', 4);
insert into subject (name, grade) values ('Philosophy', 5);
insert into subject (name, grade) values ('Politics', 5);
insert into paymenttype (name) values ('DAILY');
insert into paymenttype (name) values ('WEEKLY');
insert into paymenttype (name) values ('MONTHLY');
insert into payment (type_id, amount, payment_date, student_id) values (2, 2435, '2023-04-21 07:22:43', 1);
insert into payment (type_id, amount, payment_date, student_id) values (3, 242, '2023-04-21 07:22:43', 4);
insert into payment (type_id, amount, payment_date, student_id) values (2, 2435, '2023-04-21 07:22:43', 7);
insert into payment (type_id, amount, payment_date, student_id) values (1, 24, '2023-04-21 07:22:43', 5);
insert into payment (type_id, amount, payment_date, student_id) values (1, 2435, '2023-04-21 07:22:43', 6);
insert into mark (student_id, subject_id, mark) values (2, 1, 8);
insert into mark (student_id, subject_id, mark) values (4, 4, 5);
insert into mark (student_id, subject_id, mark) values (5, 3, 9);
insert into mark (student_id, subject_id, mark) values (8, 6, 4);
insert into mark (student_id, subject_id, mark) values (9, 5, 9);
insert into mark (student_id, subject_id, mark) values (1, 2, 9);